---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default-1

spec:
  consolidation:
    enabled: false

  kubeletConfiguration:
    containerRuntime: containerd
    clusterDNS: ["172.25.0.10"]  # it still gets the DNS wrong

  labels:
    creator: karpenter
    eks.amazonaws.com/capacityType: ON_DEMAND

  limits:
    resources:
      cpu: "320"

  providerRef:
    name: default-provider

  ttlSecondsAfterEmpty: 60
  ttlSecondsUntilExpired: 2678400  # 31.0 days


  requirements:
    - key: capacity-spread
      operator: In
      values:
        - "1"
        - "2"

    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: ["c", "m", "r"]

    - key: karpenter.k8s.aws/instance-cpu
      operator: In
      values: ["8", "16"]

    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]

    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]

    - key: kubernetes.io/os
      operator: In
      values: ["linux"]

    - key: topology.kubernetes.io/zone
      operator: In
      values: ["ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2c"]
