# ingress-nginx-1

# By convention this is AZa, and runs ON_DEMAND

---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: ingress-nginx-1

spec:
  consolidation:
    enabled: true

  kubeletConfiguration:
    containerRuntime: containerd
    clusterDNS: ["172.25.0.10"] # it still gets the DNS wrong

  labels:
    app: alb-nginx-ingress-public
    creator: karpenter
    dedicated: ingress-nginx
    eks.amazonaws.com/capacityType: ON_DEMAND

  limits:
    resources:
      cpu: "12"

  providerRef:
    name: default-provider

  taints:
    - key: dedicated
      value: ingress-nginx
      effect: NoSchedule

  # ttlSecondsAfterEmpty: 60  # mutually exclusive with consolidation
  ttlSecondsUntilExpired: 2678400 # 31 days

  requirements:
    - key: capacity-spread
      operator: In
      values:
        - "1"

    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: ["a", "c", "m", "r", "t", "x", "z"]

    - key: karpenter.k8s.aws/instance-cpu
      operator: In
      values: ["2"]

    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]

    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]

    - key: kubernetes.io/os
      operator: In
      values: ["linux"]

    - key: topology.kubernetes.io/zone
      operator: In
      values: ["ap-southeast-2a", "ap-southeast-2b", "ap-southeast-2c"]
