---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default-provider

spec:
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        deleteOnTermination: true
        encrypted: true

  instanceProfile: datalake-nonprod-1-node-role

  securityGroupSelector:
    # sg-0a475e8ca3f431386	datalake-nonprod-1-NodeGroup
    # sg-0bf21e1bcc3606205  datalake-nonprod-1-LoadBalancers
    aws-ids: "sg-0a475e8ca3f431386,sg-0bf21e1bcc3606205"

  subnetSelector:
    # Select using AWS Tags, on the subnet
    Name: datalake-nonprod-private-*
