---

repositories:
  - name: eks
    url: https://aws.github.io/eks-charts

# load in yaml anchors for helmfiles `Release Template` feature
{{ readFile "../../common/common.yaml" }}
releases:
  # load name, chart and namespace from ./versions.yaml
  - <<: *common_releases

    # This prevents helmfile exiting when it encounters a missing file
    missingFileHandler: Warn
    values:
      - ./values/values-common.yaml
      - ./values/values-{{ requiredEnv "CLUSTER" }}.yaml
    set:
      - name: clusterName
        value: {{ requiredEnv "CLUSTER" }}
      - name: serviceAccount.name
        value: {{ requiredEnv "CLUSTER" }}-eks-aws-load-balancer-controller-iam-role
      - name: region
        value: {{ requiredEnv "AWS_REGION" }}
      - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
        value: arn:aws:iam::{{ requiredEnv "AWS_ACCOUNT_ID" }}:role/{{ requiredEnv "CLUSTER"}}-eks-aws-load-balancer-controller-iam-role
      - name: image.repository
        value: 602401143452.dkr.ecr.ap-southeast-2.amazonaws.com/amazon/aws-load-balancer-controller
