---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubernetes-ro
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubernetes-ro
subjects:
  - kind: Group
    name: kubernetes-ro
    apiGroup: rbac.authorization.k8s.io
