# yaml-language-server: $schema=../schemas/build-schema.json
---
awsAccountID: "123456789013"
environment: "dev"

networking:
  vpcCidr: 10.0.0.0/20
  eksTags: true
  maxAzs: 2

eksConfig:
  eksVersion: "1.30"
  adminRoleName: "AWSReservedSSO_AdministratorAccess_03ad70a269de0fe1"
  coreNode:
    maxCount: 1
    minCount: 1
    instance: "SPOT"
    instanceSize: "large"
    instanceClass: "m5"
  eksAddOns:
    karpenter:
      version: "0.36.2"
    kubePrometheusStack:
      version: "61.6.1"
    metricsServer:
      version: "3.12.1"
    awsForFluentBit:
      version: "0.1.34"
