---
init:
  image:
    region: ap-southeast-2

image:
  region: ap-southeast-2

# The CNI supports a number of environment variable settings
# See https://github.com/aws/amazon-vpc-cni-k8s#cni-configuration-variables
env:
  ADDITIONAL_ENI_TAGS:
    - "aws-cni": "true"
  AWS_VPC_K8S_CNI_LOG_FILE: stdout
  AWS_VPC_K8S_CNI_LOGLEVEL: INFO
  AWS_VPC_K8S_PLUGIN_LOG_FILE: stderr
  AWS_VPC_K8S_PLUGIN_LOG_LEVEL: INFO
  ENABLE_PREFIX_DELEGATION: "false"  # setting true, set fire to datalake-nonprod-1 😱  => switch off globally for safety. YMMV / your funeral 💀
  MINIMUM_IP_TARGET: "20"  # reduce IP consumption
  WARM_IP_TARGET: "3"  # reduce IP consumption

podAnnotations:
  prometheus.io/port: 61678
  prometheus.io/scrape: true

resources:
  limits:
    cpu: 500m
    memory: 100Mi
  requests:
    memory: 10Mi
    cpu: 25m
