---

replicaCount: 2

resources:
  limits:
    cpu: 400m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

# we create the alb ingressclass elsewhere
createIngressClassResource: false

enableShield: false
enableWaf: false
enableWafv2: false

logLevel: info

podDisruptionBudget:
  maxUnavailable: 1


# May run on cluster-core MNG
tolerations:
  - key: dedicated
    value: cluster-core
    effect: NoSchedule

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      # Try and run on ondemand nodes
      - weight: 100
        preference:
          matchExpressions:
            - key: eks.amazonaws.com/capacityType
              operator: In
              values:
                - ON_DEMAND
      # Try and run cluster-core MNG
      - weight: 50
        preference:
          matchExpressions:
            - key: dedicated
              operator: In
              values:
                - cluster-core

topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: aws-load-balancer-controller
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: ScheduleAnyway
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: aws-load-balancer-controller
