---

additionalAnnotations:
  prometheus.io/port: "8080"
  prometheus.io/scrape: "true"

replicas: 3

# run on cluster-core Managed Node Group(s)
nodeSelector:
  dedicated: cluster-core

affinity:
  nodeAffinity:
    # Never run on a node I've provisioned (noting they have expiry times)
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: karpenter.sh/provisioner-name
              operator: DoesNotExist
    # Try and run on a ON_DEMAND
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 90
        preference:
          matchExpressions:
            - key: eks.amazonaws.com/capacityType
              operator: In
              values:
                - ON_DEMAND
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      # use different ec2 hosts
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - karpenter
          topologyKey: kubernetes.io/hostname
      # spread out across AZs
      - weight: 80
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                  - karpenter
          topologyKey: failure-domain.beta.kubernetes.io/zone


tolerations:
  - key: dedicated
    value: cluster-core
    effect: NoSchedule


controller:
  resources:
    requests:
      cpu: 1
      memory: 1Gi
    limits:
      cpu: 1
      memory: 1Gi


settings:
  # The maximum length of a batch window. The longer this is, the more pods we can consider for provisioning at one
  # time which usually results in fewer but larger nodes.
  batchMaxDuration: 10s

  # The maximum amount of time with no new ending pods that if exceeded ends the current batching window. If pods arrive
  # faster than this time, the batching window will be extended up to the maxDuration. If they arrive slower, the pods
  # will be batched separately.
  batchIdleDuration: 1s
