---

repositories:
  - name: jetstack
    url: https://charts.jetstack.io

# load in yaml anchors for helmfiles `Release Template` feature
{{ readFile "../../common/common.yaml" }}
releases:
  # load name, chart and namespace from ./versions.yaml
  - <<: *common_releases

    # This prevents helmfile exiting when it encounters a missing file
    missingFileHandler: Warn
    values:
      - ./values/values-common.yaml
