---

commandArgs:
  - --configmap=overprovisioner
  - --logtostderr=true
  - --namespace=overprovisioner
  - --target=deployment/overprovisioner-pause-pod
  - --nodelabels=count-for-overprovisioner=true  # only count nodes with labels `count-for-overprovisioner=true`
  - --v=2

ladder: |-
  {
    "nodesToReplicas":
    [
      [   1, 1 ],
      [   2, 2 ],
      [   3, 3 ],
      [   4, 4 ],
      [   5, 5 ],
      [   6, 6 ],
      [   7, 7 ],
      [   8, 8 ],
      [   9, 9 ],
      [  10, 10 ]
    ]
  }

pausepods:
  image:
    repository: k8s.gcr.io/pause
    tag: 3.5
    pullPolicy: IfNotPresent

  # Just enough to help a bit
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi

  tolerations: []

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: proportional-autoscaler-overprovisioner
                operator: In
                values:
                  - "true"
        - weight: 90
          preference:
            matchExpressions:
              - key: eks.amazonaws.com/capacityType
                operator: In
                values:
                  - SPOT
